--------------------------------------------------------
--  File created - poniedzia³ek-czerwca-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence MESSAGES_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "PRZYKLADOWY"."MESSAGES_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRODUCTS_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "PRZYKLADOWY"."PRODUCTS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RATINGS_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "PRZYKLADOWY"."RATINGS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "PRZYKLADOWY"."USERS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "PRZYKLADOWY"."PRODUCTS" 
   (	"ID_PRODUCTS" NUMBER(10,0), 
	"ID_USER" NUMBER(10,0), 
	"PRICE" NUMBER(6,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"IMAGE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PRZYKLADOWY"."USERS" 
   (	"ID_USER" NUMBER(10,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(60 BYTE), 
	"FIRST_NAME" VARCHAR2(40 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"E_MAIL" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRZYKLADOWY.PRODUCTS
SET DEFINE OFF;
Insert into PRZYKLADOWY.PRODUCTS (ID_PRODUCTS,ID_USER,PRICE,DESCRIPTION,IMAGE) values ('61','1','230','Pink roses ','https://cdn.pixabay.com/photo/2018/01/09/22/51/rose-3072698_960_720.jpg');
Insert into PRZYKLADOWY.PRODUCTS (ID_PRODUCTS,ID_USER,PRICE,DESCRIPTION,IMAGE) values ('161','2','150','Dandelion','https://cdn.pixabay.com/photo/2021/05/19/14/31/dandelion-6266230_960_720.jpg');
Insert into PRZYKLADOWY.PRODUCTS (ID_PRODUCTS,ID_USER,PRICE,DESCRIPTION,IMAGE) values ('162','2','300','Waves','https://cdn.pixabay.com/photo/2021/06/04/15/51/coast-6310250_960_720.jpg');
REM INSERTING into PRZYKLADOWY.USERS
SET DEFINE OFF;
Insert into PRZYKLADOWY.USERS (ID_USER,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,E_MAIL) values ('101','adam_adam','adam','Adam','Kowalczyk','adam_k@wp.pl');
Insert into PRZYKLADOWY.USERS (ID_USER,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,E_MAIL) values ('121','KasiaK','823e3faa4136b36a31317d3403f88204','Kasia','Kowalczuk','kasia_k@wp.pl');
Insert into PRZYKLADOWY.USERS (ID_USER,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,E_MAIL) values ('1','jan_kowalski','haslo123','Jan','Kowalski','jan@wp.pl');
Insert into PRZYKLADOWY.USERS (ID_USER,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,E_MAIL) values ('2','ryndak_p','bazy_danych','Patrycja','Ryndak','ryndak.patrycja@wp.pl');
Insert into PRZYKLADOWY.USERS (ID_USER,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,E_MAIL) values ('21','Test','098f6bcd4621d373cade4e832627b4f6','Test','Test','test@test.pl');
Insert into PRZYKLADOWY.USERS (ID_USER,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,E_MAIL) values ('81','Test2','ad0234829205b9033196ba818f7a872b','Test2','Test2','test2@wp.pl');
--------------------------------------------------------
--  DDL for Index ID_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRZYKLADOWY"."ID_USER" ON "PRZYKLADOWY"."USERS" ("ID_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_PRODUCTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRZYKLADOWY"."ID_PRODUCTS" ON "PRZYKLADOWY"."PRODUCTS" ("ID_PRODUCTS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PRODUCTS_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PRZYKLADOWY"."PRODUCTS_ON_INSERT" 
  BEFORE INSERT ON Products
  FOR EACH ROW
BEGIN
  SELECT products_sequence.nextval
  INTO :new.id_products
  FROM dual;
END;
/
ALTER TRIGGER "PRZYKLADOWY"."PRODUCTS_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PRZYKLADOWY"."USERS_ON_INSERT" 
  BEFORE INSERT ON Users
  FOR EACH ROW
BEGIN
  SELECT users_sequence.nextval
  INTO :new.id_user
  FROM dual;
END;
/
ALTER TRIGGER "PRZYKLADOWY"."USERS_ON_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PRZYKLADOWY"."USERS" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."USERS" MODIFY ("E_MAIL" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRZYKLADOWY"."USERS" ADD UNIQUE ("E_MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRZYKLADOWY"."USERS" ADD CONSTRAINT "ID_USER" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "PRZYKLADOWY"."PRODUCTS" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."PRODUCTS" MODIFY ("ID_PRODUCTS" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."PRODUCTS" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."PRODUCTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PRZYKLADOWY"."PRODUCTS" ADD CONSTRAINT "ID_PRODUCTS" PRIMARY KEY ("ID_PRODUCTS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "PRZYKLADOWY"."PRODUCTS" ADD CONSTRAINT "ID_USER_FK_PRODUCTS" FOREIGN KEY ("ID_USER")
	  REFERENCES "PRZYKLADOWY"."USERS" ("ID_USER") ENABLE;
